#ifndef ROBOT_EVENTS_H
#define ROBOT_EVENTS_H

#include <stdint.h>

/**
 * @brief Categories of events exchanged between robot tasks.
 */
typedef enum : uint8_t{
    EVENT_TOUCH,
    EVENT_MOTION,
    EVENT_POWER,
    EVENT_FOCUS,
    EVENT_NETWORK,
    EVENT_CALENDAR
} RobotEventType;

/**
 * @brief Generic event exchanged between tasks.
 */
typedef struct{
    RobotEventType type;
    uint8_t id;
} RobotEvent;

/**
 * @brief Touch events generated by the TTP223 sensor.
 */
typedef enum : uint8_t{
    TOUCH_EVENT_SINGLE,
    TOUCH_EVENT_DOUBLE,
    TOUCH_EVENT_LONG
} TouchEvent;

/**
 * @brief Motion events generated by the MPU6050.
 */
typedef enum : uint8_t{
    MOTION_EVENT_EDGE_DETECTED,
    MOTION_EVENT_SHAKE,
    MOTION_EVENT_FALL
} MotionEvent;

/**
 * @brief Power management events.
 */
typedef enum : uint8_t{
    POWER_EVENT_LOW_BATTERY,
    POWER_EVENT_POWER_SAVING_ENABLED,
    POWER_EVENT_POWER_SAVING_DISABLED
} PowerEvent;

/**
 * @brief Focus mode events.
 */
typedef enum : uint8_t{
    FOCUS_EVENT_STARTED,
    FOCUS_EVENT_FINISHED
} FocusEvent;

/**
 * @brief Calendar events.
 */
typedef enum : uint8_t{
    CALENDAR_EVENT_REMINDER
} CalendarEvent;

/**
 * @brief Connectivity events.
 */
typedef enum : uint8_t{
    NETWORK_EVENT_PC_CONNECTED,
    NETWORK_EVENT_PC_DISCONNECTED
} NetworkEvent;

#endif